Ramesha waseem 911007






                                          
                                                #numpy task 1 to 5

In [ ]:
import numpy as np

In [ ]:
marks = np.array([10, 20, 30, 40, 50])

print(np.sum(marks))
print(np.average(marks))
print(np.max(marks))
print(np.min(marks))


150
30.0
50
10


In [ ]:


marks = np.array([45, 80, 30, 90, 55, 20])
print(marks [marks >=50] )

[80 90 55]


In [ ]:


marks = np.array([1, 2, 3, 4, 5, 6])
new_marks = marks.reshape(2,3)

print(new_marks)

[[1 2 3]
 [4 5 6]]


In [ ]:
marks = np.random.randint(40, 101, 10)

print(marks)
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

[72 42 84 50 60 73 44 58 73 97]
65.3
97
42


In [ ]:
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = marks[marks >= 50]
failed = marks[marks < 50]

print(passed)
print(failed)
print(len(passed))
print(len(failed))


[67 89 90 70 58]
[35 45 22]
5
3
